philips-software/docker-ci-scripts

- CHANGELOG.md
- README.md
- docker_build.sh
- docker_push.sh
See README.md for more details on this fix.
```
Make sure you set the following environment variables:
- DOCKER_USERNAME --> Docker hub username
- DOCKER_PASSWORD --> Docker hub password
- DOCKER_ORGANIZATION --> Container will be pushed in this organization. f.e. philipssoftware
Optional environment variable:
- GITHUB_ORGANIZATION --> Github organization. defaults to DOCKER_ORGANIZATION. f.e. philips-software
```
Closes #1
> Customizes GITHUB and DOCKER organizations

- CHANGELOG.md
- docker_push.sh
No longer need to change the directory since the images are already build.
Closes #3
> Removes changing directory in push script

- docker_build.sh
- docker_build_and_push.sh
- docker_push.sh
> :bug: Fix: Uses set to force exit on fail

- docker_build.sh
> Repairs REPO link in images

- CHANGELOG.md
- README.md
- docker_build.sh
- docker_build_and_push.sh
Setup directories default for Github Actions. 
For travis-ci usage, you can still use the branch `travis-ci`
> Prepare for actions

- MAINTAINERS.md
- docker_build_and_push.sh
> Improve help message in case of an error

- CHANGELOG.md
- Dockerfile
- LICENSE.md
- README.md
- action.yml
- docker_build_and_push.sh
- docker_push.sh
- entrypoint.sh
Create a github action with this functionality.
See #10
> add script as github action

- CHANGELOG.md
- Dockerfile
- docker_push.sh
- update_readme.sh
> Automatically updates description / readme on Docker Hub

- .github/workflows/shell-linter.yml
- CHANGELOG.md
Switch to shell-linter v0.3.0
See: https://github.com/azohra/shell-linter/releases/tag/v0.3.0
> fix shelllinter

- CHANGELOG.md
- README.md
- action.yml
- docker_build.sh
- docker_push.sh
- entrypoint.sh
DOCKER_ORGANIZATION is optional for non docker hub registries.
Closes #32, #33
> Moves DOCKER_REGISTRY from arg to environment.

- CHANGELOG.md
- README.md
- docker_push.sh
> Set docker_organization

- README.md
- docker_build.sh
- docker_build_and_push.sh
- entrypoint.sh
Resolves #20 . Instead of specifying the dockerfile name I figured we can just have the user supply the entire path themselves since the path is a required field anyways.
> Change path to include dockerfile

- README.md
- action.yml
- docker_build_and_push.sh
- entrypoint.sh
> Support multiple push branches

- CHANGELOG.md
- docker_build_and_push.sh
> loop through whole array of push-branches

- CHANGELOG.md
- docker_push.sh
This fix will run the script for the right directory.
```
https://github.com/philips-software/docker-bats/runs/1154065110?check_suite_focus=true#step:4:208
```
> Fix readme update on docker hub.

- action.yml
> Push by default on 'master' or 'main'

- .github/dependabot.yml
> Add dependabot configuration to check weekly for updates

- .github/workflows/action-docs.yml
- README.md
Automate things you can automate..
> use action-docs for creating the readme

- action.yml
- docker_build_and_push.sh
Add an output `push-indicator` when pushed in a matched push branch.
Closes #89
> Add push-indicator

- .github/workflows/action-docs.yml
- Dockerfile
We do not do `master` anymore in 2022.
> Replace master with main

- container_digest.sh
Using `mktemp` to generate a temporary file
https://github.com/philips-software/docker-tern/runs/5007515003?check_suite_focus=true
Closes #103, #99
> Use temporary file to store temporary things

- README.md
Made a couple of small corrections in the README.md file.
> Corrected some typos in README.md

- container_digest.sh
Use `jq` to compact the output.
> Remove formatting from sbom. The sbom is huge.

- README.md
> Add info on COSIGN_DOCKER_MEDIA_TYPES

- bin/install_slsa_provenance.sh
> Update version of SLSA-provenance

- container_digest.sh
- docker_push.sh
- update_readme.sh
Use new released Job Summary to put a nice overview of the tasks.
> Add summary on end of the steps

- bin/install_slsa_provenance.sh
Version 0.8.0 of SLSA-provenance-action has been release.
https://github.com/philips-labs/slsa-provenance-action/releases/tag/v0.8.0
> update slsa-provenance version to 0.8.0

- README.md
- docker_build.sh
Adding support for Docker build arguments
> feat: add support for build arguments

- CHANGELOG.md
- LICENSE.md
- README.md
- container_digest.sh
- docker_build.sh
- docker_push.sh
- entrypoint.sh
- update_readme.sh
See PR #135 for more info on this change.
Addition:
- Added deprecation warnings.
Closes #135
> Add deprecation warnings: Feature/34 remave docker variables

- container_digest.sh
- docker_build_and_push.sh
closes #144
I will test this in another project
> Replace deprecated set-output

- README.md
- bin/install_cosign.sh
- container_digest.sh
For public container images we can use SigStore / Rekor / Fulcio to use keyless signing.
> Keyless signing

- container_digest.sh
Fix bug introduced by keyless signing
Closes #155
See: https://github.com/JeroenKnoops/test-docker-ci-scripts/actions/runs/3393944442
Note: This script needs some refactoring.. I will do this in a separate issue.
> Fix sign with your own keys.

- CHANGELOG.md
- README.md
- action.yml
- entrypoint.sh
Change Deprecations into Errors.
> Prepare for release

- update_readme.sh
> Update readme on Docker.io

- .github/workflows/check-vulnerabilities-docker-ci-scripts.yaml
- .github/workflows/update-docker-image.yml
- action.yml
Do not build the docker image every run... only when it needs to be changed...
> Optimize workflow

- .github/workflows/action-docs.yml
- .github/workflows/check-vulnerabilities-docker-ci-scripts.yaml
- .github/workflows/check-vulnerabilities.yaml
- .github/workflows/shell-linter.yml
- .github/workflows/update-docker-image.yml
I've used [Ratchet](https://github.com/sethvargo/ratchet) to pin the versions.
Commandline:
```
find . -name "*.yml" -path "./.github/workflows/*" -exec ratchet pin {} \;
```
> Add pinned versions of github actions

- .github/workflows/update-docker-image.yml
Created tagged version of image when an release is made.
> Create tagged version of image

- release-please-config.json
Add release-please-config.json
> Add release-please-config.json

- README.md
- bin/install_cosign.sh
Also fixes URL to community search instance
> download cosign from GitHub instead of Google Cloud Storage
